### PR TITLE
Fix build for OSX + Node 12

### LINKED ISSUE #5: Failing to build
I was going to try this module out, but it fails to build on my macOS Catalina machine with the following error when trying a `yarn add`:

```
error /path/to/project/node_modules/posix-semaphore: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /path/to/project/node_modules/posix-semaphore
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.3.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/15.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/path/to/project/node_modules/posix-semaphore/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/15.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/erin/Library/Caches/node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/15.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/erin/Library/Caches/node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/path/to/project/node_modules/posix-semaphore',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/srcs/semaphore.o
../srcs/semaphore.cc:25:9: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
    if (sem_getvalue(this->semaphore, &sval)) sval = -1;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:187:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
../srcs/semaphore.cc:54:38: error: too few arguments to function call, single argument 'context' was not specified
  constructor.Reset(tpl->GetFunction());
                    ~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:6497:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../srcs/semaphore.cc:55:73: error: too few arguments to function call, single argument 'context' was not specified
  exports->Set(Nan::New("Semaphore").ToLocalChecked(), tpl->GetFunction());
                                                       ~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:6497:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../srcs/semaphore.cc:83:34: error: too few arguments to function call, single argument 'isolate' was not specified
  strict = info[1]->BooleanValue();
           ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:2904:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
../srcs/semaphore.cc:84:33: error: too few arguments to function call, single argument 'isolate' was not specified
  debug = info[2]->BooleanValue();
          ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:2904:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
../srcs/semaphore.cc:85:34: error: too few arguments to function call, single argument 'isolate' was not specified
  silent = info[3]->BooleanValue();
           ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:2904:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
../srcs/semaphore.cc:86:42: error: too few arguments to function call, single argument 'isolate' was not specified
  retry_on_eintr = info[4]->BooleanValue();
                   ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:2904:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
../srcs/semaphore.cc:87:58: error: too few arguments to function call, single argument 'context' was not specified
  value = !info[5]->IsUndefined()? info[5]->IntegerValue(): 1;
                                   ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:2909:3: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../srcs/semaphore.cc:88:47: error: too few arguments to function call, single argument 'context' was not specified
  v8::String::Utf8Value str(info[0]->ToString());
                            ~~~~~~~~~~~~~~~~~ ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8.h:2856:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/erin/Library/Caches/node-gyp/15.3.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../srcs/semaphore.cc:114:9: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
    if (sem_getvalue(obj->semaphore, &sval)) sval = -1;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:187:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
../srcs/semaphore.cc:144:9: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
    if (sem_getvalue(obj->semaphore, &sval)) sval = -1;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:187:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
../srcs/semaphore.cc:165:9: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
    if (sem_getvalue(obj->semaphore, &sval)) sval = -1;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:187:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
../srcs/semaphore.cc:180:9: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
    if (sem_getvalue(obj->semaphore, &sval)) sval = -1;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:187:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
5 warnings and 8 errors generated.
make: *** [Release/obj.target/addon/srcs/semaphore.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/15.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/Cellar/node/15.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /path/to/project/node_modules/posix-semaphore
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v7.1.2
```

Thought you might appreciate a heads up. Let me know if you need any further info about my system.

**EDIT**: Updated error output after fixing macOS command line tools warnings.

### PR DESCRIPTION
**Pull request by szymonWojdat**
- remove `sem_getvalue` calls
- update to newest version of nan API

closes #5

### CODE REVIEW

File: srcs/semaphore.cc [hunk 1]
```diff
@@ -80,40 +75,38 @@ void Semaphore::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
   info.GetReturnValue().Set(info.This());
 }
 
 void Semaphore::Acquire(const Nan::FunctionCallbackInfo<v8::Value>& info)
 {
-  int        r;
+  int r;
   Semaphore* obj = ObjectWrap::Unwrap<Semaphore>(info.Holder());
 
-  /*if (!obj->strict && (obj->closed || obj->locked))
```
Comment (dbousque) [inline srcs/semaphore.cc:102]: Is there a reason to remove this block? Maybe it was left out after your were done debugging?

File: srcs/semaphore.cc [hunk 2]
```diff
@@ -139,59 +132,32 @@ void Semaphore::Acquire(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
-    if (sem_getvalue(obj->semaphore, &sval)) sval = -1;
-    printf("[posix-semaphore] After sem_wait, value = %d\n", sval);
-  }
 }
 
 void Semaphore::Release(const Nan::FunctionCallbackInfo<v8::Value>& info)
 {
   Semaphore* obj = ObjectWrap::Unwrap<Semaphore>(info.Holder());
-  
-  /*if (!obj->strict && (obj->closed || !obj->locked))
```
Comment (dbousque) [inline srcs/semaphore.cc:153]: Is there a reason to remove this block? Maybe it was left out after you were done debugging?

File: srcs/semaphore.cc [hunk 3]
```diff
@@ -139,59 +132,32 @@ void Semaphore::Acquire(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
-    if (sem_getvalue(obj->semaphore, &sval)) sval = -1;
-    printf("[posix-semaphore] After sem_post, value = %d\n", sval);
-  }
 }
 
 void Semaphore::Close(const Nan::FunctionCallbackInfo<v8::Value>& info)
 {
   Semaphore* obj = ObjectWrap::Unwrap<Semaphore>(info.Holder());
 
-  /*if (!obj->strict && obj->closed)
```
Comment (dbousque) [inline srcs/semaphore.cc:189]: Is there a reason to remove this block? Maybe it was left out after you were done debugging?

File: srcs/semaphore.cc [hunk 4]
```diff
@@ -80,40 +75,38 @@ void Semaphore::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
+  std::string str(*v8str);
+  strcpy(buf, str.c_str());
+
+  size_t str_len;
+  str_len = str.length();
+  if (str_len >= SEMSIZE || str_len <= 0)
+  {
+    char msg[100];
+    sprintf(msg, "Semaphore(): first argument's length must be < %i && > 0", SEMSIZE);
+    return Nan::ThrowError(msg);
```
Comment (dbousque) [inline srcs/semaphore.cc]: Is it safe to pass a local string to this constructor (is the constructor making a copy?)? If we don't know for sure, it would be better to hardcode the message.

File: srcs/semaphore.cc [hunk 5]
```diff
@@ -80,40 +75,38 @@ void Semaphore::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
-  buf = (char*)(*str);
-  Semaphore* obj = new Semaphore(buf, str.length(), strict, debug, silent, retry_on_eintr, value);
+  strict = Nan::To<bool>(info[1]).FromJust();
+  debug = Nan::To<bool>(info[1]).FromJust();
+  silent = Nan::To<bool>(info[1]).FromJust();
+  retry_on_eintr = Nan::To<bool>(info[1]).FromJust();
+  value = !info[5]->IsUndefined()? info[5]->IntegerValue(context).FromJust(): 1;
+  v8::String::Utf8Value v8str(isolate, info[0]);
+  std::string str(*v8str);
+  strcpy(buf, str.c_str());
```
Comment (dbousque) [inline srcs/semaphore.cc]: Do we know that V8 strings are null-terminated? You could use `strncpy` and manually add a terminating NULL as an alternative maybe.

**Review by dbousque — COMMENTED** [review]
Thanks a lot! Just a few things need to be cleared.

File: srcs/semaphore.cc (hunk 1 above)
Comment (dbousque) [reply srcs/semaphore.cc:102]: Ah sorry, failed to see that it was commented out.

File: srcs/semaphore.cc (hunk 2 above)
Comment (dbousque) [reply srcs/semaphore.cc:153]: Ah sorry, failed to see that it was commented out.

File: srcs/semaphore.cc (hunk 3 above)
Comment (dbousque) [reply srcs/semaphore.cc:189]: Ah sorry, failed to see that it was commented out.

File: srcs/semaphore.cc [hunk 6]
```diff
@@ -80,40 +75,38 @@ void Semaphore::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
-  silent = info[3]->BooleanValue();
-  retry_on_eintr = info[4]->BooleanValue();
-  value = !info[5]->IsUndefined()? info[5]->IntegerValue(): 1;
-  v8::String::Utf8Value str(info[0]->ToString());
-  if (str.length() >= 255 || str.length() <= 0)
-    return Nan::ThrowError("Semaphore() : first argument's length must be < 255 && > 0");
-  buf = (char*)(*str);
-  Semaphore* obj = new Semaphore(buf, str.length(), strict, debug, silent, retry_on_eintr, value);
+  strict = Nan::To<bool>(info[1]).FromJust();
+  debug = Nan::To<bool>(info[1]).FromJust();
```
Comment (dbousque) [inline srcs/semaphore.cc]: Should be `info[2]`

File: srcs/semaphore.cc [hunk 7]
```diff
@@ -80,40 +75,38 @@ void Semaphore::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
+  silent = Nan::To<bool>(info[1]).FromJust();
```
Comment (dbousque) [inline srcs/semaphore.cc]: Should be `info[3]`

File: srcs/semaphore.cc [hunk 8]
```diff
@@ -80,40 +75,38 @@ void Semaphore::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
...
+  retry_on_eintr = Nan::To<bool>(info[1]).FromJust();
```
Comment (dbousque) [inline srcs/semaphore.cc]: Should be `info[4]`

File: srcs/semaphore.cc (hunk 4 above)
Comment (szymonWojdat) [reply srcs/semaphore.cc]: The [reference](https://github.com/nodejs/nan/blob/master/doc/errors.md#api_nan_throw_error) doesn't say anything about that, I'll just revert

File: srcs/semaphore.cc (hunk 5 above)
Comment (szymonWojdat) [reply srcs/semaphore.cc]: Sure sounds good

File: srcs/semaphore.cc (hunk 6 above)
Comment (szymonWojdat) [reply srcs/semaphore.cc]: done

File: srcs/semaphore.cc (hunk 7 above)
Comment (szymonWojdat) [reply srcs/semaphore.cc]: done

File: srcs/semaphore.cc (hunk 8 above)
Comment (szymonWojdat) [reply srcs/semaphore.cc]: done

**Comment by szymonWojdat** [comment]
Thanks for taking a look so quickly. Adjusted as per comments.

**Comment by dbousque** [comment]
Thanks @szymonWojdat !

**Comment by szymonWojdat** [comment]
@dbousque FYI i just noticed that the build has failed, i think it didn't even manage to pull the code properly https://travis-ci.org/github/dbousque/posix-semaphore/jobs/752659175

**Comment by dbousque** [comment]
Thanks, I fixed it in master and deployed the new version as 1.0.0.
